version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "centre_formation"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "PHW#84#jeor"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
